import { IngredienteInventario, RecetaProducto } from "./types";

export const ingredientesBase: IngredienteInventario[] = [
  {
    id: 1,
    nombre: "Pan hamburguesa",
    categoria: "Panadería",
    unidad: "pieza",
    stock: 100,
    stockMinimo: 20,
    costoUnitario: 6,
    activo: true,
  },
  {
    id: 2,
    nombre: "Carne hamburguesa",
    categoria: "Proteína",
    unidad: "pieza",
    stock: 100,
    stockMinimo: 20,
    costoUnitario: 18,
    activo: true,
  },
  {
    id: 3,
    nombre: "Queso amarillo",
    categoria: "Lácteos",
    unidad: "pieza",
    stock: 100,
    stockMinimo: 20,
    costoUnitario: 4,
    activo: true,
  },
  {
    id: 4,
    nombre: "Tocino",
    categoria: "Proteína",
    unidad: "pieza",
    stock: 80,
    stockMinimo: 15,
    costoUnitario: 5,
    activo: true,
  },
  {
    id: 5,
    nombre: "Piña",
    categoria: "Fruta",
    unidad: "pieza",
    stock: 60,
    stockMinimo: 10,
    costoUnitario: 3,
    activo: true,
  },
  {
    id: 6,
    nombre: "Lechuga",
    categoria: "Verdura",
    unidad: "gramo",
    stock: 3000,
    stockMinimo: 500,
    costoUnitario: 0.03,
    activo: true,
  },
  {
    id: 7,
    nombre: "Jitomate",
    categoria: "Verdura",
    unidad: "gramo",
    stock: 2500,
    stockMinimo: 500,
    costoUnitario: 0.04,
    activo: true,
  },
  {
    id: 8,
    nombre: "Cebolla",
    categoria: "Verdura",
    unidad: "gramo",
    stock: 2000,
    stockMinimo: 400,
    costoUnitario: 0.03,
    activo: true,
  },
  {
    id: 9,
    nombre: "Papas",
    categoria: "Complementos",
    unidad: "gramo",
    stock: 5000,
    stockMinimo: 1000,
    costoUnitario: 0.04,
    activo: true,
  },
  {
    id: 10,
    nombre: "Refresco",
    categoria: "Bebidas",
    unidad: "pieza",
    stock: 120,
    stockMinimo: 20,
    costoUnitario: 14,
    activo: true,
  },
];

export const recetasBase: RecetaProducto[] = [
  {
    id: 1,
    productoId: 2,
    nombreProducto: "HAMBURGUESA CLÁSICA",
    activo: true,
    ingredientesBase: [
      { ingredienteId: 1, cantidad: 1 },
      { ingredienteId: 2, cantidad: 1 },
      { ingredienteId: 3, cantidad: 1 },
      { ingredienteId: 6, cantidad: 20 },
      { ingredienteId: 7, cantidad: 20 },
      { ingredienteId: 8, cantidad: 10 },
    ],
    variantes: [
      {
        nombreVariante: "Sencilla",
        ingredientes: [],
      },
      {
        nombreVariante: "Doble",
        ingredientes: [
          { ingredienteId: 2, cantidad: 1 },
          { ingredienteId: 3, cantidad: 1 },
        ],
      },
      {
        nombreVariante: "Combo Sencillo",
        ingredientes: [
          { ingredienteId: 9, cantidad: 150 },
          { ingredienteId: 10, cantidad: 1 },
        ],
      },
      {
        nombreVariante: "Combo Doble",
        ingredientes: [
          { ingredienteId: 2, cantidad: 1 },
          { ingredienteId: 3, cantidad: 1 },
          { ingredienteId: 9, cantidad: 150 },
          { ingredienteId: 10, cantidad: 1 },
        ],
      },
    ],
  },
];